# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 00:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('five_day_avg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sixteen_day_avg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('country', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CityTemperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('visability', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('date_created', models.DateField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeatherRangerProject.City')),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_in_range', models.BooleanField()),
                ('is_in_five_day_range', models.BooleanField()),
                ('is_in_sixteen_day_range', models.BooleanField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeatherRangerProject.City')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
