# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherRangerProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='five_day_avg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='sixteen_day_avg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
